"""
Django settings for boardly_project project.

Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-some-secret-key' # Потрібно замінити на безпечний ключ у продакшені

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def _split_env(value: str) -> list[str]:
    return [item.strip() for item in value.split(',') if item.strip()]

ALLOWED_HOSTS = _split_env(os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1'))
ALLOWED_HOSTS.extend(_split_env(os.getenv('ALLOWED_HOSTS_EXTRA', '')))


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps (тут можуть бути пакети для REST API, аутентифікації тощо)
    'rest_framework',
    'corsheaders', 
    'rest_framework.authtoken',
    'djoser', # ДОДАНО: Для управления аутентифікацією (реєстрація, логін)
    
    # My apps
    'core', # Реєструємо наш основний додаток для моделей

    # Google authentication apps
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # ВАЖЛИВО: CORS MiddleWare має бути першим або дуже рано
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'boardly_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'boardly_project.wsgi.application'


# Database
# Налаштування PostgreSQL, як ми обговорили
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

POSTGRES_DB = os.getenv('POSTGRES_DB')
POSTGRES_USER = os.getenv('POSTGRES_USER')
POSTGRES_PASSWORD = os.getenv('POSTGRES_PASSWORD')
POSTGRES_HOST = os.getenv('POSTGRES_HOST')
POSTGRES_PORT = os.getenv('POSTGRES_PORT')

# Якщо POSTGRES env не задані, працюємо на SQLite (dev fallback).
USE_POSTGRES = any([POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT])

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': POSTGRES_DB or 'boardly_db',
            'USER': POSTGRES_USER or 'wanderingonlyup',
            'PASSWORD': POSTGRES_PASSWORD or 'admin123',
            'HOST': POSTGRES_HOST or 'localhost',
            'PORT': POSTGRES_PORT or '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'uk' # Змінюємо на українську

TIME_ZONE = 'Europe/Kyiv' # Встановлюємо часовий пояс України

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------------------------
# CORS / ФРОНТЕНД НАЛАШТУВАННЯ
# ----------------------------------------------------------------------

# Адреса, з якої React буде надсилати запити (зазвичай порт 3000)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Додаткові origins з env (через кому), наприклад для ngrok
extra_origins = os.getenv('CORS_EXTRA_ORIGINS')
if extra_origins:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in extra_origins.split(',') if o.strip()])

# CSRF trusted origins (comma-separated), e.g. https://<front-ngrok>,https://<back-ngrok>
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
extra_csrf = os.getenv('CSRF_TRUSTED_ORIGINS')
if extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in extra_csrf.split(',') if o.strip()])

# Дозволяємо надсилати cookies та заголовки авторизації (важливо для аутентифікації)
CORS_ALLOW_CREDENTIALS = True 

# ----------------------------------------------------------------------
# DJANGO REST FRAMEWORK (DRF) НАЛАШТУВАННЯ
# ----------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', 
        # 'rest_framework.authentication.SessionAuthentication', 
    ],
    # Встановлюємо дозвіл за замовчуванням (усі методи заборонені, якщо не вказано інше)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# 1. Налаштування Email (для розробки виводимо в консоль)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Коли будемо готові до продакшну, замінимо на SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# 2. Налаштування Djoser
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'password-reset/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'username-reset/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    'SERIALIZERS': {
        'user_create': 'core.api.serializers.UserCreateSerializer',
        'user': 'core.api.serializers.UserSerializer',
        'current_user': 'core.api.serializers.UserSerializer',
    },
}

# 3. Налаштування Social Auth (Google)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': '374249918192-1mtc1h12qqq33tvrj4g7jkbqat8udrbk.apps.googleusercontent.com', # Встав сюди ID з консолі
            'secret': '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', # Встав сюди Secret
            'key': ''
        }
    }
}

# Важливо для dj-rest-auth: вимикаємо перевірку email для соціальних акаунтів, щоб не було помилок
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False