# Generated by Django 6.0 on 2025-12-04 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Картки')),
                ('description', models.TextField(blank=True, verbose_name='Опис Картки')),
                ('order', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Позиція')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Кінцевий термін')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архівувати Картку')),
            ],
            options={
                'verbose_name': 'Картка',
                'verbose_name_plural': 'Картки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва Дошки')),
                ('description', models.TextField(blank=True, verbose_name='Опис Дошки')),
                ('background_url', models.CharField(blank=True, max_length=255, verbose_name='Фон Дошки')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архівувати Дошку')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Обрана Дошка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('invite_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Посилання-запрошення')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL, verbose_name='Власник')),
            ],
            options={
                'verbose_name': 'Дошка',
                'verbose_name_plural': 'Дошки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card', verbose_name='Картка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Призначення Картки',
                'verbose_name_plural': 'Призначення Карток',
                'unique_together': {('card', 'user')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='members',
            field=models.ManyToManyField(related_name='assigned_cards', through='core.CardMember', to=settings.AUTH_USER_MODEL, verbose_name='Призначені учасники'),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва Списку')),
                ('order', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Позиція')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архівувати Список')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='core.board', verbose_name='Дошка')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.list', verbose_name='Список'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('member', 'Учасник')], default='member', max_length=50, verbose_name='Роль')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board', verbose_name='Дошка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Участь у Дошці',
                'verbose_name_plural': 'Участь у Дошках',
                'unique_together': {('user', 'board')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', through='core.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Учасники'),
        ),
    ]
