# Generated by Django 6.0 on 2025-12-04 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_board_cardmember_card_members_list_card_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.TextField(verbose_name='Опис дії')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час дії')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.board', verbose_name='Дошка')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Дія',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва чек-листа')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.card', verbose_name='Картка')),
            ],
            options={
                'verbose_name': 'Чек-лист',
                'verbose_name_plural': 'Чек-листи',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст підзадачі')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Виконано')),
                ('order', models.IntegerField(default=0, verbose_name='Позиція')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.checklist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункти чек-листів',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва мітки')),
                ('color', models.CharField(max_length=7, verbose_name='Колір (HEX)')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='core.board', verbose_name='Дошка')),
            ],
            options={
                'verbose_name': 'Мітка',
                'verbose_name_plural': 'Мітки',
                'unique_together': {('board', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CardLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card', verbose_name='Картка')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.label', verbose_name='Мітка')),
            ],
            options={
                'verbose_name': 'Присвоєння мітки',
                'verbose_name_plural': 'Присвоєння міток',
                'unique_together': {('card', 'label')},
            },
        ),
    ]
