# Generated by Django 6.0 on 2025-12-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_checklist_checklistitem_label_cardlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('CREATE_BOARD', 'Створення дошки'), ('UPDATE_BOARD', 'Оновлення дошки'), ('CREATE_LIST', 'Створення списку'), ('MOVE_LIST', 'Переміщення списку'), ('CREATE_CARD', 'Створення картки'), ('MOVE_CARD', 'Переміщення картки'), ('UPDATE_CARD', 'Оновлення картки'), ('ARCHIVE_CARD', 'Архівування картки'), ('MEMBER_JOIN', 'Приєднання учасника')], default='CREATE_CARD', max_length=50, verbose_name='Тип дії'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID цілі'),
        ),
    ]
