# Generated by Django 5.0 on 2025-12-26 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_action_type_activity_target_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlabel',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='core.card', verbose_name='Картка'),
        ),
        migrations.AlterField(
            model_name='cardlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_labels', to='core.label', verbose_name='Мітка'),
        ),
        migrations.RenameModel(
            old_name='Membership',
            new_name='BoardMember',
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'verbose_name': 'Учасник Дошки', 'verbose_name_plural': 'Учасники Дошки', 'db_table': 'core_membership'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.board', verbose_name='Дошка'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', through='core.BoardMember', to=settings.AUTH_USER_MODEL, verbose_name='Учасники'),
        ),
        migrations.CreateModel(
            name='FavoriteBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обрана Дошка',
                'verbose_name_plural': 'Обрані Дошки',
                'unique_together': {('user', 'board')},
            },
        ),
    ]
