# Generated by Django 5.2.10 on 2026-01-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attachment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English')], default='uk', max_length=10, verbose_name='Мова'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Email-повідомлення'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Дія')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Тип сутності')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID сутності')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Дані')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час дії')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог дій',
                'verbose_name_plural': 'Логи дій',
                'ordering': ['-created_at'],
            },
        ),
    ]
