# Generated by Django 5.2 on 2026-01-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_avatar_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог д?й', 'verbose_name_plural': 'Логи д?й'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Д?я'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час д?ї'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID сутност?'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип сутност?'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дан?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish')], default='uk', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Email notifications'),
        ),
    ]
