# Generated by Django 5.2 on 2026-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_activitylog_options_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_url',
            field=models.TextField(blank=True, verbose_name='Фон Дошки'),
        ),
    ]
