# Generated by Django 5.2 on 2026-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_board_background_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Колір Картки (HEX)'),
        ),
    ]
