# Generated by Django 5.2.10 on 2026-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_card_card_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог дій', 'verbose_name_plural': 'Логи дій'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час дії'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID сутності'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип сутності'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дані'),
        ),
    ]
