# Generated by Django 5.2.10 on 2026-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activitylog_options_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В обраному'),
        ),
    ]
