# Generated by Django 5.2.10 on 2026-01-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_board_is_favorite_membership_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публічна картка'),
        ),
    ]
