# Generated by Django 5.2.10 on 2026-01-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_bio'),
        ('core', '0012_card_is_public'),
    ]

    operations = [
    ]
