# Generated by Django 5.2 on 2026-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_0008_profile_bio_0012_card_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_board_view',
            field=models.CharField(choices=[('kanban', 'Kanban'), ('calendar', 'Calendar')], default='kanban', max_length=20, verbose_name='Default board view'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_added',
            field=models.BooleanField(default=True, verbose_name='Added to board notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_assigned',
            field=models.BooleanField(default=True, verbose_name='Assigned task notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_desktop',
            field=models.BooleanField(default=True, verbose_name='Desktop notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_due',
            field=models.BooleanField(default=True, verbose_name='Due date notifications'),
        ),
        migrations.AddField(
            model_name='profile',
            name='require_login_verification',
            field=models.BooleanField(default=False, verbose_name='Require login verification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_timeout',
            field=models.CharField(default='1h', max_length=20, verbose_name='Session timeout'),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Two-factor enabled'),
        ),
    ]
