# Generated by Django 5.2 on 2026-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_profile_pending_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last due reminder sent at'),
        ),
        migrations.AddField(
            model_name='card',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10, verbose_name='Recurring schedule'),
        ),
        migrations.AddField(
            model_name='card',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reminder minutes before due date'),
        ),
    ]
